# Generated by Django 4.2.11 on 2024-09-18 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='عنوان محصول:')),
                ('image', models.ImageField(upload_to='', verbose_name='تصویر محصول:')),
                ('price', models.FloatField(verbose_name='قیمت محصول:')),
                ('discription', models.TextField(verbose_name='توضیحات:')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_product', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده:')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
